### PR TITLE
Remove miner-related posts and mentionings

### PR DESCRIPTION
**Pull request by itsjuoum**
The FalixCoins miner has been archived, therefore, documentation for it is no longer needed.

### CODE REVIEW

**Comment by Mocab** [comment]
I think it would be better to use the guide to inform others that the miner has been archived

**Comment by Mocab** [comment]
you can remove it after a few weeks

**Comment by itsjuoum** [comment]
@Mocab I agree that we should let people know what happened to the miner, although I think that an announcement at the Discord server or an alert box in the help center's index should do it. If we keep the article, it won't be a "guide" anymore.

**Comment by Mocab** [comment]
yeah that might be a better idea, it might be a good idea to remind users in the desktop app as well, if they click "miner" they should see the message that informs them about the miner

**Comment by itsjuoum** [comment]
> it might be a good idea to remind users in the desktop app as well, if they click "miner" they should see the message that informs them about the miner

Agreed.

**Review by KorbsStudio — APPROVED** [review]

**Review by DaddyChimken — APPROVED** [review]

**Pull request merged**
